# SFS specific settings
name: SFS

n_rep: 5
n_candidate_peak: 5
n_candidate_pb: 5
bool_force_sfs_acc: False

n_fold: 10
bool_use_strat_kfold: True
random_seed: null


width: 5
max_width: 10

bool_tune_hyperparams: False