main:
  source: file
  user: ${oc.env:USER}

defaults:
  - _self_
  - meta: ???
  - patient: ???
  - data_paths: dynamics_subsec_step3
  - logging: default_wandb
  - preproc: ur0_1s
  - feature_selection: sfs_settings_dynamics
  - parallel: home_ray_cpu_batch
  - tune: base_no_tune_default
  - dynamics: dynamics_subsec_default

exp_type: "Dynamics_subSec"

hydra:
  sweeper:
    params:
      meta: glob(*, exclude=[base*, default*, *no_run*])
      patient: glob(*, exclude=*no_run*)