source: database
database_module: duckdb
database_path: /media/shortterm_ssd/Clay/databases/duckdb/rcs-db.duckdb
query: select * from overnight.r${device}_epoched_enveloped; # select * from overnight.r${device}; # where SessionIdentity='02R_04-30-22';

# Can do a multi-line query like this:
# query: |
#   select * from 
#   r${device}.overnight_simulated_FFTs_train
# (Use > instead of | if you want line breaks to be interpreted as spaces by python script)
