main:
  source: file
  user: ${oc.env:USER}

defaults:
  - _self_
  - meta: med_LDA_auc_default
  - patient: RCS02R
  - data_paths: model_id_step3
  - preproc: ur1_5s
  - feature_selection: sfs_settings_default
  - parallel: home_ray_cpu_batch
  # - parallel: no_ray
  - dynamics: no_dynamics_default
