defaults:
  - _self_
  - early_stopping: ${evaluation.early_stopping.torch_default}

model_name: EEGNetModel
parameters:
    chunk_size: 128
    num_electrodes: 1 # TODO: IF in_channels = 1 and num_electrodes = 3, then error is thrown...
    in_channels: 15
    F1: 15
    F2: 6
    D: 15
    n_class: 5
    kernel_1: 64
    kernel_2: 16
    dropout: 0.25
    linear_input_size: 2808
    n_epoch: 30
    batch_size: 64