defaults:
  - base_model
  - _self_

model_args: []
model_kwargs:
  loss: 'log_loss'
  learning_rate: 0.1
  n_estimators: 100
  subsample: 1.0
  criterion: 'friedman_mse'
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_depth: 3
  min_impurity_decrease: 0.0
  init: null
  random_state: null
  max_features: null
  verbose: 0
  max_leaf_nodes: null
  warm_start: False
  validation_fraction: 0.1
  n_iter_no_change: null
  tol: 1e-4
  ccp_alpha: 0.0

ensemble_args: []
ensemble_kwargs: {}

model_type: 'sklearn'