defaults:
  - base_model
  - _self_

model_args:
  type: 'SVM'

model_kwargs:
  C: 1.0
  kernel: 'rbf'
  degree: 3
  gamma: 'scale'
  coef0: 0.0
  shrinking: True
  probability: True # modifed from default
  tol: 1e-3
  cache_size: 200
  class_weight: null
  verbose: False
  max_iter: -1
  decision_function_shape: 'ovr'
  break_ties: False
  random_state: null

ensemble_args: []
ensemble_kwargs:
  n_estimators: 50
  learning_rate: 1.0
  algorithm: 'SAMME.R'
  random_state: null

model_type: 'sklearn'